# nind-denoise Configuration File
# 
# This YAML configuration file defines the settings for the nind-denoise application,
# including model paths, external tool configurations, processing operations, and
# supported file formats.

# Models Section
# Defines available neural network models for denoising operations.
# Each model entry contains:
#   - path: File system path to the model file
#   - default: (optional) Boolean indicating if this is the default model
models:
  nind_generator_650.pt:
    path: "models/brummer2019/generator_650.pt"
    # Uncomment the line below to make this the default model
    # default: true

# Tools Section  
# Platform-specific configurations for external command-line tools.
# Tools are organized by platform (windows/posix) and each tool defines:
#   - path: Full path to the executable
#   - args: List of default command-line arguments
tools:
  # Windows-specific tool paths
  windows:
    darktable:
      path: "C:\\Program Files\\darktable\\bin\\darktable-cli.exe"
      args: "[]"# Add arguments to pass here if needed
    gmic:
      path: "C:\\Program Files\\gmic-cli\\gmic.exe"
      args: "[]"# Add arguments to pass here if needed
  # POSIX (Linux/macOS) tool paths
  posix:
    darktable:
      path: "/usr/bin/darktable-cli"
      args: "[]"# Add arguments to pass here if needed
    gmic:
      path: "/usr/bin/gmic"
      args: "[]"# Add arguments to pass here if needed

# Operations Section
# Defines the processing pipeline operations and their execution stages.
# Operations are divided into first_stage and second_stage for the pipeline.
# Nightmode operations can be moved between stages based on runtime settings.
operations:
  # First stage operations (applied during initial processing)
  first_stage:
    - channelmixerrgb
    - colorin
    - colorout
    - demosaic
    - flip
    - gamma
    - highlights
    - hotpixels
    - mask_manager
    - rawprepare
    - temperature
  # Second stage operations (applied after denoising)
  second_stage:
    - ashift
    - bilat
    - blurs
    - borders
    - colorbalancergb
    - colorin
    - colorout
    - crop
    - cacorrectrgb
    - clahe
    - denoiseprofile
    - diffuse
    - dither
    - exposure
    - filmicrgb
    - flip
    - gamma
    - hazeremoval
    - invert
    - lens
    - levels
    - liquify
    - lowlight
    - lut3d
    - mask_manager
    - monochrome
    - nlmeans
    - rgbcurve
    - rgblevels
    - rotatepixels
    - scalepixels
    - shadhi
    - sharpen
    - soften
    - splittoning
    - spots
    - tonecurve
    - tonemap
    - toneequal
    - velvia
    - vibrance
    - vignette
    - watermark
    - zonesystem

  overrides:
    colorin:
      darktable:blendop_params: gz11eJxjYIAACQYYOOHEgAZY0QWAgBGLGANDgz0Ej1Q+dcF/IADRAGpyHQU=
      darktable:blendop_version: '14'
      darktable:enabled: '1'
      darktable:modversion: '7'
      darktable:multi_name: ''
      darktable:multi_name_hand_edited: '0'
      darktable:multi_priority: '0'
      darktable:num: '0'
      darktable:operation: colorin
      darktable:params: gz48eJxjZBgFowABWAbaAaNgwAEAEDgABg==
  
  # Nightmode operations that get moved from second_stage to first_stage
  # when nightmode is enabled
  nightmode_ops:
    - exposure        # Move exposure to first stage for nightmode
    - toneequal       # Move tone equalization to first stage for nightmode

# Valid Extensions Section
# List of supported raw image file extensions.
# These extensions are used for input validation and file filtering.
valid_extensions:
  - 3FR   # Hasselblad
  - ARW   # Sony
  - SR2   # Sony
  - SRF   # Sony
  - CR2   # Canon
  - CR3   # Canon
  - CRW   # Canon
  - DNG   # Adobe Digital Negative
  - ERF   # Epson
  - FFF   # Imacon/Hasselblad
  - MRW   # Minolta
  - NEF   # Nikon
  - NRW   # Nikon
  - ORF   # Olympus
  - PEF   # Pentax
  - RAF   # Fujifilm
  - RW2   # Panasonic
export:
  - outpath = ""
  - jpeg_quality: "90"
rldeblur:
  sigma: "1"
  iterations: "10"