# Default CLI configuration for nind-denoise
# Values here are used for import-time defaults (e.g., valid_extensions)

valid_extensions:
  - 3FR
  - ARW
  - SR2
  - SRF
  - CR2
  - CR3
  - CRW
  - DNG
  - ERF
  - FFF
  - MRW
  - NEF
  - NRW
  - ORF
  - PEF
  - RAF
  - RW2
