valid_extensions:
  - 3FR
  - ARW
  - SR2
  - SRF
  - CR2
  - CR3
  - CRW
  - DNG
  - ERF
  - FFF
  - MRW
  - NEF
  - NRW
  - ORF
  - PEF
  - RAF
  - RW2
# Configuration for CLI pipeline
default_parameters:
  input_dir: "./input"
  output_dir: "./output"
  model_path: "./model.pth"
  batch_size: 32
  num_workers: 4
tools:
  windows:
    darktable: "C:\\Program Files\\darktable\\bin\\darktable-cli.exe"
    gmic: "~\\gmic-3.6.1-cli-win64\\gmic.exe"
  linux:
    darktable: "/usr/bin/darktable-cli"
    gmic: "/usr/bin/gmic"
